{% set name = "eups" %}
{% set version = "2.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RobertLuptonTheGood/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 095e18b6079c49bdba48355edcb479b0b1b91a9013cafdf00ca112e596b0885b

build:
  number: 0

requirements:
  build:
    - make

  host:
    - python
    - git
    - make

  run:
    - python

about:
  home: https://github.com/RobertLuptonTheGood/eups
  license: GPL-2.0-or-later
  license_family: GPL
  summary: 'A version manager tracking product dependencies'

extra:
  recipe-maintainers:
    - gcomoretto
    - bvan
